insert into Libraries (LibraryID , LibraryName) values (1, 'Emmerich, Moore and Smith');
insert into Libraries (LibraryID , LibraryName) values (2, 'Hagenes Group');
insert into Libraries (LibraryID , LibraryName) values (3, 'Cassin Inc');
insert into Libraries (LibraryID , LibraryName) values (4, 'Kris LLC');
insert into Libraries (LibraryID , LibraryName) values (5, 'Armstrong, Cormier and Littel');
insert into Libraries (LibraryID , LibraryName) values (6, 'Ferry-Gottlieb');
insert into Libraries (LibraryID , LibraryName) values (7, 'Gottlieb-Hauck');
insert into Libraries (LibraryID , LibraryName) values (8, 'Grimes, Mills and Lockman');
insert into Libraries (LibraryID , LibraryName) values (9, 'Funk LLC');
insert into Libraries (LibraryID , LibraryName) values (10, 'Schuppe-Prohaska');
insert into Libraries (LibraryID , LibraryName) values (11, 'Effertz LLC');
insert into Libraries (LibraryID , LibraryName) values (12, 'Bruen-Becker');
insert into Libraries (LibraryID , LibraryName) values (13, 'Hahn-Graham');
insert into Libraries (LibraryID , LibraryName) values (14, 'Bailey LLC');
insert into Libraries (LibraryID , LibraryName) values (15, 'Stracke LLC');
insert into Libraries (LibraryID , LibraryName) values (16, 'Lesch-Rosenbaum');
insert into Libraries (LibraryID , LibraryName) values (17, 'Ernser Inc');
insert into Libraries (LibraryID , LibraryName) values (18, 'Becker-Feeney');
insert into Libraries (LibraryID , LibraryName) values (19, 'Muller-Schoen');
insert into Libraries (LibraryID , LibraryName) values (20, 'Larkin, Blick and Harvey');
insert into Libraries (LibraryID , LibraryName) values (21, 'Rohan, Legros and Upton');
insert into Libraries (LibraryID , LibraryName) values (22, 'Ernser-Bayer');
insert into Libraries (LibraryID , LibraryName) values (23, 'Farrell LLC');
insert into Libraries (LibraryID , LibraryName) values (24, 'Larson-Nicolas');
insert into Libraries (LibraryID , LibraryName) values (25, 'Waters, Anderson and Stokes');
insert into Libraries (LibraryID , LibraryName) values (26, 'Stark-Rosenbaum');
insert into Libraries (LibraryID , LibraryName) values (27, 'Toy, Rempel and Hirthe');
insert into Libraries (LibraryID , LibraryName) values (28, 'Barrows-Leannon');
insert into Libraries (LibraryID , LibraryName) values (29, 'Quitzon, Abbott and Carter');
insert into Libraries (LibraryID , LibraryName) values (30, 'Jones LLC');
insert into Libraries (LibraryID , LibraryName) values (31, 'Beatty, Bauch and Frami');
insert into Libraries (LibraryID , LibraryName) values (32, 'Rutherford-Walsh');
insert into Libraries (LibraryID , LibraryName) values (33, 'Bruen, Hoppe and Fadel');
insert into Libraries (LibraryID , LibraryName) values (34, 'Rutherford-Flatley');
insert into Libraries (LibraryID , LibraryName) values (35, 'McCullough, Aufderhar and Skiles');
insert into Libraries (LibraryID , LibraryName) values (36, 'Kshlerin, Koelpin and Bernhard');
insert into Libraries (LibraryID , LibraryName) values (37, 'Mills, Goyette and Larkin');
insert into Libraries (LibraryID , LibraryName) values (38, 'Prosacco Inc');
insert into Libraries (LibraryID , LibraryName) values (39, 'Collier, Pacocha and Jenkins');
insert into Libraries (LibraryID , LibraryName) values (40, 'Von, Mueller and Schmidt');
insert into Libraries (LibraryID , LibraryName) values (41, 'Sporer Group');
insert into Libraries (LibraryID , LibraryName) values (42, 'Crooks, Mertz and Gorczany');
insert into Libraries (LibraryID , LibraryName) values (43, 'Mohr, Roberts and Rogahn');
insert into Libraries (LibraryID , LibraryName) values (44, 'Fahey-Hagenes');
insert into Libraries (LibraryID , LibraryName) values (45, 'Ortiz, Brown and Prosacco');
insert into Libraries (LibraryID , LibraryName) values (46, 'Gleason, O''Reilly and Harber');
insert into Libraries (LibraryID , LibraryName) values (47, 'McCullough, Gibson and Schmitt');
insert into Libraries (LibraryID , LibraryName) values (48, 'Doyle-Prohaska');
insert into Libraries (LibraryID , LibraryName) values (49, 'Beer-Lesch');
insert into Libraries (LibraryID , LibraryName) values (50, 'Senger, Walter and Rath');
