insert into Libraries (LibraryID , LibraryName) values (1, 'Legros-Ullrich');
insert into Libraries (LibraryID , LibraryName) values (2, 'Lubowitz-Kunde');
insert into Libraries (LibraryID , LibraryName) values (3, 'Lebsack Inc');
insert into Libraries (LibraryID , LibraryName) values (4, 'Christiansen-Kozey');
insert into Libraries (LibraryID , LibraryName) values (5, 'Towne, Leuschke and Waters');
insert into Libraries (LibraryID , LibraryName) values (6, 'Donnelly Group');
insert into Libraries (LibraryID , LibraryName) values (7, 'Casper, Steuber and Schoen');
insert into Libraries (LibraryID , LibraryName) values (8, 'Towne, Roberts and Price');
insert into Libraries (LibraryID , LibraryName) values (9, 'Leuschke-Bechtelar');
insert into Libraries (LibraryID , LibraryName) values (10, 'Konopelski-O''Hara');
insert into Libraries (LibraryID , LibraryName) values (11, 'Rutherford-Lebsack');
insert into Libraries (LibraryID , LibraryName) values (12, 'Barrows Group');
insert into Libraries (LibraryID , LibraryName) values (13, 'Herman LLC');
insert into Libraries (LibraryID , LibraryName) values (14, 'Cormier LLC');
insert into Libraries (LibraryID , LibraryName) values (15, 'Champlin and Sons');
insert into Libraries (LibraryID , LibraryName) values (16, 'Durgan Inc');
insert into Libraries (LibraryID , LibraryName) values (17, 'Steuber LLC');
insert into Libraries (LibraryID , LibraryName) values (18, 'Hermiston-MacGyver');
insert into Libraries (LibraryID , LibraryName) values (19, 'Franecki-Ernser');
insert into Libraries (LibraryID , LibraryName) values (20, 'Hackett LLC');
insert into Libraries (LibraryID , LibraryName) values (21, 'Veum, Rogahn and Boyle');
insert into Libraries (LibraryID , LibraryName) values (22, 'Quigley-Conroy');
insert into Libraries (LibraryID , LibraryName) values (23, 'Kautzer-Senger');
insert into Libraries (LibraryID , LibraryName) values (24, 'DuBuque-Kihn');
insert into Libraries (LibraryID , LibraryName) values (25, 'Braun, Vandervort and Gutmann');
insert into Libraries (LibraryID , LibraryName) values (26, 'White and Sons');
insert into Libraries (LibraryID , LibraryName) values (27, 'Bashirian, Von and Wiegand');
insert into Libraries (LibraryID , LibraryName) values (28, 'Beer, Graham and MacGyver');
insert into Libraries (LibraryID , LibraryName) values (29, 'Sporer Group');
insert into Libraries (LibraryID , LibraryName) values (30, 'Zulauf Group');
insert into Libraries (LibraryID , LibraryName) values (31, 'Rohan-Fisher');
insert into Libraries (LibraryID , LibraryName) values (32, 'Nienow-Kuhlman');
insert into Libraries (LibraryID , LibraryName) values (33, 'Kuvalis Inc');
insert into Libraries (LibraryID , LibraryName) values (34, 'Feil-Spinka');
insert into Libraries (LibraryID , LibraryName) values (35, 'Mayer Group');
insert into Libraries (LibraryID , LibraryName) values (36, 'Will-Kuhn');
insert into Libraries (LibraryID , LibraryName) values (37, 'Bayer-Maggio');
insert into Libraries (LibraryID , LibraryName) values (38, 'Roob Group');
insert into Libraries (LibraryID , LibraryName) values (39, 'Simonis Group');
insert into Libraries (LibraryID , LibraryName) values (40, 'Dickens-Dibbert');
insert into Libraries (LibraryID , LibraryName) values (41, 'Legros LLC');
insert into Libraries (LibraryID , LibraryName) values (42, 'Schulist Group');
insert into Libraries (LibraryID , LibraryName) values (43, 'Heidenreich, Haag and Wuckert');
insert into Libraries (LibraryID , LibraryName) values (44, 'Wehner LLC');
insert into Libraries (LibraryID , LibraryName) values (45, 'Shanahan, Padberg and Hilpert');
insert into Libraries (LibraryID , LibraryName) values (46, 'Towne-Leuschke');
insert into Libraries (LibraryID , LibraryName) values (47, 'Frami, Huels and Senger');
insert into Libraries (LibraryID , LibraryName) values (48, 'Kreiger, Hodkiewicz and Schinner');
insert into Libraries (LibraryID , LibraryName) values (49, 'Hirthe and Sons');
insert into Libraries (LibraryID , LibraryName) values (50, 'Jerde, Rath and Brown');
